image: node:8

cache:
  paths:
  - node_modules/

deploy:
  stage: deploy
  script: "scp -R ./docs www@dev-server:/home/www/wikis/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
  environment:
    name: development
