image: node:8

make doc:
  script:

  # try to clone yourself, the SSH_PRIVATE_KEY was added as deploy key to this repository
  - > 
    if git diff HEAD~ --name-only|grep docs; then
        ssh www@localhost "mkdir -p /home/www/docs/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
        scp -r ./docs/* www@localhost:/home/www/docs/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/
    fi;
